routes/web.php
Route::get('/admin/add/branch', 'Admin\BranchController@addbranch')->name('admin.add.branch');
Route::post('/admin/insert/branch', 'Admin\BranchController@insertbranch')->name('admin.insert.branch');
Route::get('/admin/all/branch', 'Admin\BranchController@viewbranch')->name('admin.view.branch');
Route::get('/admin/delete/branch/{brance_id}', 'Admin\BranchController@deletebranch')->name('admin.delete.branch');
Route::get('/admin/edit/branch/{brance_id}', 'Admin\BranchController@editbranch')->name('admin.edit.branch');
Route::post('/admin/branch/update', 'Admin\BranchController@updatebranch')->name('admin.update.branch');
//Admin Bank  Controller
Route::group(['prefix' => 'admin'], function() {
Route::get('/add/bank', 'Admin\BankController@addbank')->name('admin.add.bank');
Route::post('/insert/bank', 'Admin\BankController@insertbank')->name('admin.insert.bank');
Route::get('/delete/bank/{bank_id}', 'Admin\BankController@deletebank')->name('admin.delete.bank');
Route::get('/edit/bank/{bank_id}', 'Admin\BankController@editbank')->name('admin.edit.bank');
Route::post('/bank/update', 'Admin\BankController@updatebank')->name('admin.update.bank');
// Route::get('/single/bank/{bank_id}', 'Admin\BankController@banksingleview')->name('admin.single.bank');
});
//Admin Bank  Controller
Route::group(['prefix' => 'admin'], function() {
Route::get('/add/bankholder', 'Admin\BankholderController@addbankholder')->name('admin.add.bankholder');
Route::post('/insert/bankholder', 'Admin\BankholderController@insertbank')->name('admin.insert.bankholder');
Route::get('/all/bankholder', 'Admin\BankholderController@viewbank')->name('admin.view.bankholder');
Route::get('/delete/bankholder/{bankholder_id}', 'Admin\BankholderController@deletebankholder')->name('admin.delete.bankholder');
Route::get('/edit/bankholder/{bankholder_id}', 'Admin\BankholderController@editbank')->name('admin.edit.bankholder');
Route::post('/bankholder/update', 'Admin\BankholderController@updatebank')->name('admin.update.bankholder');
Route::get('/single/bankholder/{bankholder_id}', 'Admin\BankholderController@bankholdersingleview')->name('admin.single.bankholder');
});
//Admin Deposit Controller
Route::group(['prefix' => 'admin'], function() {
Route::get('/add/deposit/bank', 'Admin\DepositController@adddeposit')->name('admin.add.deposit');
Route::post('/insert/deposit/bank', 'Admin\DepositController@insertdeposit')->name('admin.insert.deposit');
Route::get('/all/deposits', 'admin\depositcontroller@viewdeposit')->name('admin.view.deposit');
Route::get('/delete/deposits/{deposit_id}', 'admin\depositcontroller@deletedeposit')->name('admin.delete.deposits');
Route::get('/edit/deposits/{deposit_id}', 'admin\depositcontroller@editdeposit')->name('admin.edit.deposits');
Route::post('/deposits/update', 'admin\depositcontroller@updatedeposit')->name('admin.update.deposits');
Route::get('/single/deposits/{deposit_id}', 'admin\depositcontroller@depositsingleview')->name('admin.single.deposits');
});
Route::get('get/holder/{bankid}','Admin\DepositController@GetHolder');
Route::get('get/details/holder/{hold_id}','Admin\DepositController@GetDetailsHolder');
Route::get('/get/pay/bank/{paybank_id}','Admin\DepositController@GetPaybank');
Route::get('/get/payment/bank/{payment_id}','Admin\DepositController@Pamentbank');
//Admin Withdraw Controller
Route::get('admin/add/withdraw/bank', 'Admin\WithdrawController@addwithdraw')->name('admin.add.withdraw');
Route::post('admin/insert/withdraw/bank', 'Admin\WithdrawController@insertwithdraw')->name('admin.insert.withdraw');
Route::get('admin/all/withdraw', 'admin\WithdrawController@viewwithdraw')->name('admin.view.withdraw');
Route::get('admin/delete/withdraw/{withdraw_id}', 'admin\WithdrawController@deletewithdraw')->name('admin.delete.withdraw');
Route::get('admin/edit/withdraw/{withdraw_id}', 'admin\WithdrawController@editwithdraw')->name('admin.edit.withdraw');
Route::post('admin/withdraw/update', 'admin\WithdrawController@updatewithdraw')->name('admin.update.withdraw');
Route::get('/single/withdraw/{withdraw_id}', 'admin\WithdrawController@withdrawsingleview')->name('admin.single.withdraw');
//Admin Loan Controller
Route::post('admin/insert/loanfrom/bank', 'Admin\LoanController@insertloanfrom')->name('admin.insert.loanfrom');
Route::get('admin/delete/loanfrom/{loanfrom_id}', 'admin\LoanController@deleteloanfrom')->name('admin.delete.loanfrom');
Route::get('admin/edit/loanfrom/{loanfrom_id}', 'admin\LoanController@editloanfrom')->name('admin.edit.loanfrom');
Route::post('admin/loanfrom/update', 'admin\LoanController@updateloanfrom')->name('admin.update.loanfrom');
//loan
Route::get('admin/add/loan/bank', 'Admin\LoanController@addloan')->name('admin.add.loan');
Route::post('admin/insert/loan/bank', 'Admin\LoanController@insertloan')->name('admin.insert.loan');
Route::get('admin/all/loan', 'Admin\LoanController@viewloan')->name('admin.view.loan');
Route::get('admin/delete/loan/{loan_id}', 'admin\LoanController@deleteloan')->name('admin.delete.loan');
Route::get('admin/edit/loan/{loan_id}', 'admin\LoanController@editloan')->name('admin.edit.loan');
Route::post('admin/loan/update', 'admin\LoanController@updateloan')->name('admin.update.loan');
Route::get('/single/loan/{loan_id}', 'admin\LoanController@loansingleview')->name('admin.single.loan');

//Admin POS Route 
Route::get('admin/pos/', 'Admin\PosController@addpos')->name('admin.pos');




Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as'=>'admin.'], function() {
    //admin employ route
    Route::resource('employee', 'EmployeeController');
    //admin attendance route
    Route::resource('attendance', 'AttendanceController');
    Route::post('attendance-save', 'AttendanceController@attendace')->name('save.attendance');
    Route::get('todayattendance', 'AttendanceController@attendaceshow')->name('attendance.today');
    Route::get('edittodayattendance', 'AttendanceController@editattendace')->name('attendance.today.edit');
    Route::post('updatetodayattendance', 'AttendanceController@updateattendace')->name('attendance.today.update');
    Route::get('todayattendancebtanch', 'AttendanceController@attendacebranch')->name('attendance.branch');
    Route::post('todayattendancebtanch', 'AttendanceController@branchattendacesave')->name('branch.save');

    //update today branch  attendance
    Route::get('edittodayattendancebtanch', 'AttendanceController@editattendacebranch')->name('attendance.branch.edit');
    Route::post('edittodayattendancebtanch', 'AttendanceController@editbranchattendacesave')->name('edit.branch.save');
    Route::post('branchupdatetodayattendance', 'AttendanceController@branchupdateattendace')->name('attendance.today.branch.update');


    //update all date attendance branch
    Route::get('edit-date-attendance', 'AttendanceController@editdateattendace')->name('attendance.branch.date.edit');
    Route::post('edit-date-attendance', 'AttendanceController@editdateattendacesave')->name('date.save');
    Route::post('datewiseupdate', 'AttendanceController@datewiseupdate')->name('date.update');


    Route::get('searchattendance', 'AttendanceController@search')->name('attendance.search');
    Route::post('searchattendance', 'AttendanceController@searchresult')->name('attendance.search.result');
    Route::post('searchattendancebybranch', 'AttendanceController@searchbranchdate')->name('attendance.search.branchdate');

    //search employee attendance

    Route::get('searchemployeeattendance', 'EmployeeAttendanceController@search')->name('employee.attendance.search');
    Route::post('searchemployeeattendance-show', 'EmployeeAttendanceController@searchresult')->name('employee.attendance.result');

    //search employee attendance yearly

    Route::get('search-employee-attendance-yearly', 'EmployeeAttendanceController@yearlySearch')->name('employee.attendance.yearly');
    Route::post('search-employee-attendance-yearly', 'EmployeeAttendanceController@yearlyresult')->name('employee.attendance.yearly.result');

//Account

    Route::get('get-employee-details', 'AccountController@employeeDetails')->name('employee.details');






});

Route::get('/get/employee/{branch_id}', 'Admin\EmployeeAttendanceController@searchemp');
Route::get('/get/employeeinfo/{employee_id}', 'Admin\AccountController@empInfo');





//maneger attendance route
Route::group(['prefix' => 'maneger', 'as'=>'maneger.'], function() {
    Route::resource('attendance', 'AttendanceController');
    Route::get('attendance-show', 'AttendanceController@attshow')->name('att.show');
    Route::get('edittodayattendancebranch', 'AttendanceController@editattendace')->name('att.edit');
    Route::post('edittodayattendancebranch', 'AttendanceController@updateattendacesave')->name('att.update');
    Route::get('searchattendance', 'AttendanceController@search')->name('attendance.search');
    Route::post('searchattendance', 'AttendanceController@searchresult')->name('attendance.search.result');


    //datewise update

    Route::get('datewise-edit', 'AttendanceController@dateedit')->name('date.edit');
    Route::post('edit-date-attendance', 'AttendanceController@editdatesave')->name('date.save');
    Route::post('datewiseupdate', 'AttendanceController@datewiseupdate')->name('date.update');




    //search employee attendance

    Route::get('searchemployeeattendance', 'AttendanceController@searchemployee')->name('employee.attendance.search');
    Route::post('searchemployeeattendance-show', 'AttendanceController@searcempresult')->name('employee.attendance.result');

    //search employee attendance yearly

    Route::get('search-employee-attendance-yearly', 'AttendanceController@yearlySearch')->name('employee.attendance.yearly');
    Route::post('search-employee-attendance-yearly', 'AttendanceController@yearlyresult')->name('employee.attendance.yearly.result');



});







//admin employ route
//Route::group(['prefix' => 'admin', 'as'=>'admin.'], function() {

app/Attendance.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Attendance extends Model
{
    public function employee(){
    return $this->belongsTo('App\Employee','employee_id');
}
    public function branchas(){
        return $this->belongsTo('App\User','branch');
    }
    protected $guarded = [];

}

resources/views/attendance/create.blade.php
@extends('layouts.app')
@section('content')
<script src="https://code.jquery.com/jquery-3.4.1.js"
integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
crossorigin="anonymous"></script>
<!-- content wrpper -->
<div class="content_wrapper">
	<!--middle content wrapper-->
	<!-- page content -->
	<div class="middle_content_wrapper">
		<section class="page_content">
			<div class="panel mb-0">
				<div class="panel_header">
					<div class="panel_title">
						<span class="panel_icon"><i class="fas fa-border-all"></i></span><span>Add Employee</span>
						<a href="{{route('admin.employee.create')}}" class="btn btn-success float-right">Create Employee</a>
					</div>
				</div>
				<div class="panel_body">
					<div class="row">
						<div class="col-md-10 col-xs-12 offset-1">
							<div >
								<div class="card">
									<h5 class="card-header">Add Employee</h5>
									<div class="card-body">
										@if ($errors->all())
										<div class="alert alert-danger">
											@foreach ($errors->all() as $error)
											<li>{{ $error }}</li>
											@endforeach
										</div>
										@endif
										<form action="{{route('admin.employee.store')}}" enctype="multipart/form-data" method="post">
											@csrf
											<div class="form-row">
												<div class="col-md-4 col-xs-12">
													<div class="form-group">

														<label for="exampleSelect1">Branch</label>
														<select class="form-control" name="branch">
															@foreach($branchs as $branch)
																<option value="{{$branch->id}}">{{$branch->name}}</option>
															@endforeach
															<option value="master">Main Branch</option>

														</select>

													</div>
												</div>
												<div class="col-md-4 col-xs-12">
													<div class="form-group">
														<label>Employee Name</label>
														<input type="text" class="form-control"  name="name">
													</div>
												</div>
												<div class="col-md-4 col-xs-12">
													<div class="form-group">
														<label>Email</label>
														<input type="text" class="form-control"  name="email">
													</div>
												</div>

													<div class="col-md-4 col-xs-12">
													<div class="form-group">
														<label>Mobile</label>
														<input type="mobile" class="form-control"  name="mobile" >
													       </div>
												     </div>
												<div class="col-md-4 ccol-xs-12">
													<div class="form-group">
														<label> Address</label>
														<input type="text" class="form-control" name="address" >
													</div>
												</div>
												     <div class="col-md-4 col-xs-12">
                                                       <div class="form-group">
                                                          <label>Salary</label>
														   <input type="number" class="form-control" name="salary" value="" id="salary" onkeyup="sum();">
                                                      </div>
												    </div>


												
											</div>
											<div class="form-row">
												<div class="col-md-4 col-xs-12">
													<div class="form-group">
														<label>Fax</label>
														<input type="number" class="form-control"  name="fax" value="">
													</div>
												</div>
												<div class="col-md-4 col-xs-12">
													
													<div class="form-group">
														<label>Contact person</label>
														<input type="text" class="form-control"  name="contact_person" value="">
													</div>
												</div>
												<div class="col-md-4 col-xs-12">
													<div class="form-group">
														<label>Per Day</label>
														<input type="number" class="form-control" name="perday" id="perday"  >
													</div>
												</div>

											</div>
											<div class="form-row">
												<div class="col-md-4 col-xs-12">
													<div class="form-group">
														<label>Company person</label>
														<input type="text" class="form-control"  name="company_person" value="">
													</div>
												</div>
												<div class="col-md-4 col-xs-12">
													<div class="form-group">
														<label>Bank name</label>
														<input type="text" class="form-control"  name="bank_name" value="">
													</div>
												</div>

												<div class="col-md-4 col-xs-12">
													<div class="form-group">
														<label>Account number</label>
														<input type="number" class="form-control"  name="account_number" value="">
													</div>
												</div>
												
											</div>
											
											<div class="form-row">
												<div class="col-md-4 col-xs-12">
													<div class="form-group">
														<label>Account name</label>
														<input type="text" class="form-control"  name="account_name" value="">
													</div>
												</div>
												<div class="col-md-4 col-xs-12">
													<div class="form-group">
														<label>Bank Branch</label>
														<input type="text" class="form-control"  name="bank_branch">
													</div>
												</div>
												<div class="col-md-4 col-xs-12">
													<div class="form-group">
														<label>Position</label>
														<select class="form-control"  name="position">
															<option selected>Select</option>
															<option value="Employee">Employee</option>
															<option value="manager">manager</option>

														</select>
													</div>
												</div>


												

											</div>

											<div class="form-row">
												<div class="col-md-6 col-xs-12">
													<div class="form-group">
														<label>Upload Photo</label>
														<input type="file" class="form-control"  name="image" >
													</div>
												</div>
												<div class="col-md-6 col-xs-12">
													
												</div>
												
												
											</div>
											
											<button type="submit" class="btn btn-primary">Add Employee</button>
										</form>
									</div>
								</div>
							</div>
							
						</div>
					</div>
					
				</div>
				</div> <!--/ panel body -->
				</div><!--/ panel -->
			</section>
			<!--/ page content -->
			<!-- start code here... -->
			</div><!--/middle content wrapper-->
			</div><!--/ content wrapper -->
			<script type="text/javascript">
           function sum() {
               var salary = document.getElementById('salary').value;
                var result = parseInt(salary) /28;
               if (!isNaN(result)) {
               document.getElementById('perday').value = parseInt(result);
               }
              }
             </script>
			@endsection

resources/views/attendance/dateedit.blade.php
@extends('layouts.app')
@section('content')


  <div class="content_wrapper">

    <div class="middle_content_wrapper">
      <section class="page_content">
        <div class="panel mb-0">
          <div class="panel_header">
            <div class="panel_title">
              <span class="panel_icon"><i class="fas fa-border-all"></i></span><span>Show Employee Attendance</span>
            </div>
          </div>
          <div class="panel_body">

            <div class="row">
              <div class="col-md-6 offset-md-3">
                <form action="{{route('maneger.date.save')}}" method="post">
                  @csrf

                  <div class="form-group">
                    <label for="exampleSelect1">Select Date</label>
                    <input type="date" class="form-control" name="date" required="">

                  </div>
                  <button type="submit" class="btn btn-success">Show</button>


                </form>

              </div>


            </div>


          </div>
        </div> <!--/ panel body -->


      </section>
      <!--/ page content -->
      <!-- start code here... -->

    </div><!--/middle content wrapper-->
  </div><!--/ content wrapper -->


@endsection

resources/views/attendance/dateupdate.blade.php
@extends('layouts.app')
@section('content')


<div class="content_wrapper">

  <div class="middle_content_wrapper">
    <section class="page_content">
      <div class="panel mb-0">
        <div class="panel_header">
          <div class="panel_title">
            <span class="panel_icon"><i class="fas fa-border-all"></i></span><span>Update Employee</span>
              <a class="btn btn-success float-right" href="{{route('maneger.date.update')}}">Back</a>
          </div>
        </div>
        <div class="panel_body">

         <div class="row">
             <form action="{{route('maneger.att.update')}}" method="post">
                 @csrf
             <table id="dataTableExample1" class="table table-bordered table-striped table-hover mb-2">
                 <thead>
                 <tr>
                     <th>Employee ID</th>
                     <th>Employee Name</th>
                     <th>Branch</th>
                     <th>Mobile</th>
                     <th>Image</th>
                     <th class="text-center" >Attendance</th>

                 </tr>
                 </thead>

                 <tbody>

                 @foreach($att_today as $att_t)
                     <tr>
                         <td >{{$att_t->employee->employee_id}}</td>
                         <td>{{$att_t->employee->name}}</td>
                         @if($att_t->branch =='master')
                             <td>Master</td>
                         @else
                             <td>{{$att_t->branchas->name}}</td>
                         @endif
                         <td>{{$att_t->employee->mobile}}</td>
                         <td><img id="logo" src="{{asset('public/panel/employee/'.$att_t->employee->image) }}" width="50" height="50;" /></td>

                         <td>
                             <fieldset class="form-group">

                                 <div>
                                     <label class="form-check-label">
                                         <input {{($att_t->attendance == 'present') ? 'checked' :''}} type="radio" name="attendence[{{$att_t->id}}]" id="optionsRadios1" value="present" >
                                         Present &nbsp;&nbsp;
                                         <input {{($att_t->attendance == 'absent') ? 'checked' :''}} type="radio" name="attendence[{{$att_t->id}}]" id="optionsRadios1" value="absent">
                                         Absent &nbsp;&nbsp;
                                         <input {{($att_t->attendance == 'vacation') ? 'checked' :''}} type="radio" name="attendence[{{$att_t->id}}]" id="optionsRadios1" value="vacation">
                                        Vacation
                                     </label>
                                 </div>

                             </fieldset>
                         </td>
                         <input type="hidden" name="branch[{{$att_t->id}}]" value="{{($att_t->branch =='master') ? 'master' : $att_t->branchas->id}}">
                         <input type="hidden" name="attendance_year" value="{{$att_t->attendance_year}}">
                         <input type="hidden" name="attendance_month" value="{{$att_t->attendance_month}}">
                         <input type="hidden" name="attendance_day" value="{{$att_t->attendance_day}}">
                         <input type="hidden" name="date" value="{{$att_t->date}}">
                         <input type="hidden" name="emp_id[{{$att_t->id}}]" value="{{$att_t->employee->id}}">
                         <input type="hidden" name="id[]" value="{{$att_t->id}}">




                     </tr>
                 @endforeach
                 </tbody>

             </table>
             <button type="submit" class="btn btn-success ">Update </button>
             </form>

         </div>

            
          </div>
          </div> <!--/ panel body -->


        </section>
        <!--/ page content -->
        <!-- start code here... -->

        </div><!--/middle content wrapper-->
        </div><!--/ content wrapper -->


@endsection

resources/views/attendance/edit.blade.php
@extends('layouts.app')
@section('content')
	<script src="https://code.jquery.com/jquery-3.4.1.js"
			integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
			crossorigin="anonymous"></script>
	<!-- content wrpper -->
	<div class="content_wrapper">
		<!--middle content wrapper-->
		<!-- page content -->
		<div class="middle_content_wrapper">
			<section class="page_content">
				<div class="panel mb-0">
					<div class="panel_header">
						<div class="panel_title">
							<span class="panel_icon"><i class="fas fa-border-all"></i></span><span>Edit Employee</span>
							<a href="{{route('admin.employee.create')}}" class="btn btn-success float-right">Create Employee</a>

						</div>
					</div>
					<div class="panel_body">
						<div class="row">
							<div class="col-md-10 col-xs-12 offset-1">
								<div >
									<div class="card">
										<h5 class="card-header">Add Employee</h5>
										<div class="card-body">
											@if ($errors->all())
												<div class="alert alert-danger">
													@foreach ($errors->all() as $error)
														<li>{{ $error }}</li>
													@endforeach
												</div>
											@endif
											<form action="{{route('admin.employee.update',$employee->id)}}" enctype="multipart/form-data" method="post">
												@csrf
												@method('PUT')
												<div class="form-row">
													<div class="col-md-4 col-xs-12">
														<div class="form-group">

															<label for="exampleSelect1">Branch</label>
															<select class="form-control" name="branch">
																@foreach($branchs as $branch)
																	<option value="{{$branch->id}}" @if($employee->user_id==$branch->id) selected @endif>{{$branch->name}}</option>
																@endforeach
																<option value="master">Main Branch</option>

															</select>

														</div>
													</div>
													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Employee Name</label>
															<input type="text" class="form-control" value="{{$employee->name}}"  name="name">
														</div>
													</div>
													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Email</label>
															<input type="text" class="form-control" value="{{$employee->email}}"  name="email">
														</div>
													</div>

													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Mobile</label>
															<input type="mobile" class="form-control" value="{{$employee->mobile}}"  name="mobile" >
														</div>
													</div>
													<div class="col-md-4 ccol-xs-12">
														<div class="form-group">
															<label> Address</label>
															<input type="text" value="{{$employee->address}}" class="form-control" name="address" >
														</div>
													</div>
													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Salary</label>
															<input type="number" class="form-control" name="salary" value="{{$employee->salary}}" id="salary" onkeyup="sum();">
														</div>
													</div>



												</div>
												<div class="form-row">
													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Fax</label>
															<input type="number" class="form-control"  name="fax" value="{{$employee->fax}}">
														</div>
													</div>
													<div class="col-md-4 col-xs-12">

														<div class="form-group">
															<label>Contact person</label>
															<input type="text" class="form-control"  name="contact_person" value="{{$employee->contact_person}}">
														</div>
													</div>
													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Per Day</label>
															<input type="number" class="form-control" name="perday" value="{{$employee->perday}}" id="perday"   >
														</div>
													</div>

												</div>
												<div class="form-row">
													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Company person</label>
															<input type="text" class="form-control"  name="company_person" value="{{$employee->company_person}}">
														</div>
													</div>
													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Bank name</label>
															<input type="text" class="form-control"  name="bank_name" value="{{$employee->bank_name}}">
														</div>
													</div>

													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Account number</label>
															<input type="number" class="form-control"  name="account_number" value="{{$employee->account_number}}">
														</div>
													</div>

												</div>

												<div class="form-row">
													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Account name</label>
															<input type="text" class="form-control"  name="account_name" value="{{$employee->account_name}}">
														</div>
													</div>
													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Bank Branch</label>
															<input type="text" class="form-control"  name="bank_branch" value="{{$employee->branch}}">
														</div>
													</div>
													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Position</label>
															<select class="form-control"  name="position">
																<option selected>Select</option>
																@if($employee->position =='Employee')
																	<option selected value="Employee">Employee</option>
																@else
																	<option selected value="manager">manager</option>
																@endif

															</select>
														</div>
													</div>




												</div>

												<div class="form-row">
													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<label>Upload Logo</label>
															<img src="" id="show">
															<input type="file"   name="image" id="cust_image" onchange="readURL(this);">

														</div>
														<input type="hidden" name="oldpic" value="{{$employee->image }}">
													</div>
													<div class="col-md-4 col-xs-12">
														<div class="form-group">
															<img src="{{ URL::to('public/panel/employee/'.$employee->image) }}" width="100" height="100" />
														</div>
													</div>
													<div class="col-md-4 col-xs-12">
													</div>
												</div>

												<button type="submit" class="btn btn-primary">Update Employee</button>
											</form>
										</div>
									</div>
								</div>

							</div>
						</div>

					</div>
				</div> <!--/ panel body -->
		</div><!--/ panel -->
		</section>
		<!--/ page content -->
		<!-- start code here... -->
	</div><!--/middle content wrapper-->
	</div><!--/ content wrapper -->
	<script type="text/javascript">
        function sum() {
            var salary = document.getElementById('salary').value;
            var result = parseInt(salary) /28;
            if (!isNaN(result)) {
                document.getElementById('perday').value = parseInt(result);
            }
        }
	</script>

	<script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e)
                {
                    $('#show')
                        .attr('src', e.target.result)
                        .width(80)
                        .height(80);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
	</script>
@endsection